## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [ ]:
import numpy as np
from numpy import array

a = -1.3
b = 2.5
np.arange(a, b + (b-a)/64, (b-a)/64)

array({-1.3, -1.240625, -1.18125, -1.121875, -1.0625, -1.003125,
       -0.94375, -0.884375, -0.825, -0.765625, -0.70625, -0.646875,
       -0.5875, -0.528125, -0.46875, -0.409375, -0.35, -0.290625,
       -0.23125, -0.171875, -0.1125, -0.053125, 0.00625, 0.065625,
       0.125, 0.184375, 0.24375, 0.303125, 0.3625, 0.421875,
       0.48125, 0.540625, 0.6, 0.659375, 0.71875, 0.778125,
       0.8375, 0.896875, 0.95625, 1.015625, 1.075, 1.134375,
       1.19375, 1.253125, 1.3125, 1.371875, 1.43125, 1.490625,
       1.55, 1.609375, 1.66875, 1.728125, 1.7875, 1.846875,
       1.90625, 1.965625, 2.025, 2.084375, 2.14375, 2.203125,
       2.2625, 2.321875, 2.38125, 2.440625, 2.5})

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [ ]:
n = 3
np.array([1, 2, 3] * n)
array([1, 2, 3, 1, 2, 3, 1, 2, 3])


3.	Создайте массив первых 10 нечетных целых чисел.

In [ ]:
i = 10
np.arange(1, 2 * i, 2)
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [ ]:
a = np.zeros((10, 10))
a[0, :] = 1
a[9, :] = 1
a[:, 0] = 1
a[:, 9] = 1
a
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [ ]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [ ]:
n = 10
a = np.zeros((n, n))
for i in range(len(a)):
    for j in range(len(a)):
        a[i][j] = i + j
a
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [ ]:
a = np.array([[1, 0], [4, 1]])
b = np.array([[1, 6], [6, 3]])
c = np.array([[3], [7]])
d = np.array([[3, 5, 7]])
e = np.array([[4], [5], [7]])
print('Матрица на матрицу: ' + str(np.dot(a, b)))
print('Матрица на вектор: ' + str(np.dot(a, c)))
print('Вектор на вектор: ' + str(np.dot(d, e)))
Матрица на матрицу: [[ 1  6]
 [10 27]]
Матрица на вектор: [[ 3]
 [19]]
Вектор на вектор: [[86]]

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [ ]:
cos = np.cos(np.linspace(0, 1, int(1/0.05)))
sin = np.sin(np.linspace(0, 1, int(1/0.05)))
list(cos) + list(sin)
[1.0,
 0.9986152781425827,
 0.9944649474795756,
 0.9875605021181478,
 0.9779210635311101,
 0.9655733276010717,
 0.9505514906876966,
 0.9328971549228098,
 0.912659212995635,
 0.8898937127472434,
 0.8646637019492132,
 0.8370390536963741,
 0.8070962728972044,
 0.7749182843977933,
 0.7405942033261461,
 0.7042190882928544,
 0.6658936781316236,
 0.625724112908743,
 0.5838216399741468,
 0.5403023058681398,
 0.0,
 0.05260728333807213,
 0.10506887376594912,
 0.15723948186175024,
 0.20897462406278547,
 0.2601310228046501,
 0.3105670033203749,
 0.3601428860007191,
 0.40872137322898616,
 0.4561679296190457,
 0.5023511546035125,
 0.547143146340223,
 0.5904198559291864,
 0.6320614309590333,
 0.6719525474315213,
 0.7099827291448582,
 0.7460466536513234,
 0.7800444439418607,
 0.8118819450498316,
 0.8414709848078965]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [ ]:
a = np.random.rand(3,5) * 4 - 1
a
array([[ 0.55942993,  1.44441489, -0.57242619, -0.38552636,  1.39818828],
       [ 2.12819896, -0.55719257,  0.60355055, -0.20867274, -0.06341553],
       [ 1.90085995, -0.59926023,  2.38794951,  1.79991017,  0.98021692]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [ ]:
print(np.sum(a))
print(np.sum(a, 1))
print(np.sum(a, 0)) 
print(np.average(a, 1))
print(np.var(a, 1))
print(np.std(a, 1))
10.816225525258144
[2.44408056 1.90246867 6.4696763 ]
[4.58848883 0.28796209 2.41907387 1.20571107 2.31498967]
[0.48881611 0.38049373 1.29393526]
[0.72716461 0.90553122 1.10076874]
[0.85273948 0.95159404 1.04917527]

11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [ ]:
for i in range(len(a)):
    a[i,:] -= np.average(a, 1)[i]
    a[i,:] /= np.std(a, 1)[i]
a
array([[ 0.08280819,  1.12062219, -1.24450941, -1.02533364,  1.06641266],
       [ 1.836608  , -0.9853848 ,  0.23440334, -0.61913636, -0.46649017],
       [ 0.57847788, -1.80446066,  1.04273736,  0.48225966, -0.29901424]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [ ]:
asort3 = a[a[:, 2].argsort()[::-1]]
print(asort3)
[[ 0.57847788 -1.80446066  1.04273736  0.48225966 -0.29901424]
 [ 1.836608   -0.9853848   0.23440334 -0.61913636 -0.46649017]
 [ 0.08280819  1.12062219 -1.24450941 -1.02533364  1.06641266]]

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [ ]:
b = np.dot(np.transpose(a), a)
c = np.dot(a, np.transpose(a))
print(b)
print(c)
[[ 3.71462281 -2.76080949  0.93065196 -0.94304028 -0.941425  ]
 [-2.76080949  5.48285557 -3.50718088 -1.40914265  2.19427745]
 [ 0.93065196 -3.50718088  2.69104978  1.63377989 -1.74830076]
 [-0.94304028 -1.40914265  1.63377989  1.66721329 -0.94881025]
 [-0.941425    2.19427745 -1.74830076 -0.94881025  1.44425856]]
[[ 5.-1.10652473 -4.08526202]
 [-1.10652473  5.2.92584904]
 [-4.08526202  2.92584904  5.]

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [ ]:
bsum = np.sum(np.diagonal(b))
csum = np.sum(np.diagonal(c))
print(bsum)
print(csum)
15.0
15.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [ ]:
print(np.linalg.det(b))
print(np.linalg.det(c))
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))
print(np.linalg.matrix_rank(c))
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)
print(w_b)
print(w_c)
5.390509983053748e-31
19.08049365873332
3
3
3
[ 1.05865339e+01+0.00000000e+00j  3.95811379e+00+0.00000000e+00j
  4.55352304e-01+0.00000000e+00j -3.49422559e-16+1.23529588e-16j
 -3.49422559e-16-1.23529588e-16j]
[10.58653391  0.4553523   3.95811379]

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [ ]:
np.random.seed(1032201714)
np.random.randint(9)
4
print('Аналитическое решение интеграла 4: ', np.pi/4)
print('Аналитическое решение интеграла 9: ', np.pi/(2**(3/2)))
Аналитическое решение интеграла 4:  0.7853981633974483
Аналитическое решение интеграла 9:  1.1107207345395915
def func1(x):
    return 1/(x*(1+(np.log(x)**2)))

def func2(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def solution(func,a, b, dx, method):
    n = int((b-a) / dx)
    xx = np.linspace(a, b, n)
    if method == 'rectangular':
        return dx*np.sum(func(xx))
    elif method == 'trapezoid':
        return dx/2*(func(xx[0]) + 2*np.sum(func(xx[1:-1])) + func(xx[-1]))
    elif method == 'simpson':
        return dx/3*(func(xx[0]) + 2*np.sum(func(xx[2:-1:2])) + 4*np.sum(func(xx[1:-2:2])) + func(xx[-1]))
    else:
        return 'Неверный метод'
    
print('Для интеграла 4:', solution(func1, 1, np.e, 0.0001, 'rectangular'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'rectangular') )
print('Для интеграла 4:', solution(func1, 1, np.e, 0.0001, 'trapezoid'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'trapezoid') )
print('Для интеграла 4:', solution(func1, 1, np.e, 0.0001, 'simpson'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'simpson') )
Для интеграла 4: 0.7853742503271548 Для интеграла 9: 1.1041419998928388
Для интеграла 4: 0.7853150533411256 Для интеграла 9: 1.1041172156215913
Для интеграла 4: 0.785308921070893 Для интеграла 9: 1.1032101773676126